# Generated by Django 5.2.2 on 2025-06-04 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('BOOK', 'Book'), ('MOVIE', 'Movie'), ('PAINTING', 'Painting'), ('MUSICIAN', 'Musician'), ('OTHER', 'Other')], max_length=10)),
                ('image_url', models.URLField(help_text='URL to the image of the item (cover, poster, etc.)', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Optional: Short description or relevant metadata.')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for categorization/recommendation.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSwipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(help_text='True for like (right swipe), False for dislike (left swipe)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_swipes', to='swipe.culturalitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('user', 'item')},
            },
        ),
    ]
