# Generated by Django 5.2.2 on 2025-06-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='messages_sent_by_user1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='messages_sent_by_user2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user1_requests_reveal_at_10',
            field=models.BooleanField(default=False, help_text='User1 (lower ID) requested early reveal'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user2_requests_reveal_at_10',
            field=models.BooleanField(default=False, help_text='User2 (higher ID) requested early reveal'),
        ),
    ]
