# Generated by Django 5.2.2 on 2025-06-04 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('short_bio', models.TextField(blank=True)),
                ('favorite_books', models.TextField(blank=True, help_text='List your favorite books, separated by commas.')),
                ('favorite_movies', models.TextField(blank=True, help_text='List your favorite movies, separated by commas.')),
                ('favorite_music_genres', models.TextField(blank=True, help_text='List your favorite music genres, separated by commas.')),
                ('profile_picture_url', models.URLField(blank=True, help_text='URL to the profile picture.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
